@CSIT_314_Group_HostAddress = http://localhost:5135


POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json
{
  "Name": "edwin",
  "Email": "edwin@example.com",
  "PhoneNumber": "81234567",
  "Password": "MySecret456!",
  "Profile" : "admin",
  "IsSuspended" : false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/Auth/Login
Content-Type : application/json
Accept: application/json
{
    "Email": "edwin@example.com",
     "Password": "MySecret456!"
}
###


GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount
Content-Type : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6peI31n3NPEreMQCpmp3ftpX2nrgU91enzKgwVE06Jmu6kH2Lhr2oiDImDLWhKvwjFhwNmPTtpU33YcNX4Ik2kF8KlKU2MtTRmq-vy04TaxNPhX4sUtFkAXaI4R4NG5LpvIcRmFWShGIDIwlfd0M1hszAU5H3g99C2XIU-WDuWcWq00sZ_CnDzEVC9jXjr03fvmL7zX1QizJq_uNSJJSZCeHDj1iPdHvmJexfpjTz_L94QhTWuITJWk6keA08cywjZln_pTk7yA1MrN8bt4xsvu2Wr1NnsxXcKmyK6mmJdVXxjFXYun7bdT9MJ6wz8DkJ-9QS6wdLSJtUIDgcDnx6cMJUVEDaPvrvaZTXr2041gp_3Wuuhdj2l2mStnI-iDFZgWbzi8LKKIKtY68IB7o_hMofSjykwyGHco8_SpwBdjSStpVjg3OI8ou_FwWXAsjtWVItBAYj8jz7UnOQPMLh0UJzZGdgHACt2KwFipTn0mgI8vFS1SVKdoVL6PGUWYvI_17f1ZiFb3_QSY2FSz7vDzd8JoyWjFAAZepFJyjLvXTCqyIrFOxrKhmV5QMdpKA5s6JtxStvVIIDJNCPbz1bJEYzfAo_gunPT8cGEDSdkF7hpDAKTrl3yPqJIqrxI4lfI
###

GET {{CSIT_314_Group_HostAddress}}/api/SearchUserAccount?nameOrEmailOrPhone=testNonAdmin@example.com
Content-Type : application/json

###

GET {{CSIT_314_Group_HostAddress}}/api/Auth/Logout
Content-Type : application/json


###
PUT {{CSIT_314_Group_HostAddress}}/api/SuspendUserAccount
Content-Type : application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6qsoRQ2_KqSsceMqcSELHEZLGYV9wEaZrHjMgTZ6l-49ER6nHcKUF7q9P7yLdD0WQrC84Jar_7C979FOMRoqn_puX3L4fSiF9ZTUSRs3ZIn8Hs7EbdwaozMeR-lstpNvuJ75WDlI5j_qg85REJLMqKpi6zwtSJ8azMbqfxof0gNyQbsHrHz9dMsRZN-nYUbKY851cNqWR0alvQnF8_TM1Tf0TFU3RyNYzj4zm3zeFiueSFWLDUo2Pn_qfttcOpgFvuSwD2vTS-rD3FqED9_urHNyFF5HxQHRZkofAKT-cfA7-lfPTJIFITJYGSPLIjz6BI_EIOCTj85-mtAYcOULAbiyGlSOJ2Gno9Ue_4jfmdD_ApBzvB2OHOukPuH6quZLHCLU4sM-j-GSTAtilUkIAb56Oys4MbMnPnedGWM0hKGhLEyrgwJkHRzWthzQGNkk3bz_OYjDZHFsN3J7Gqt6aJwgJjss3vf_KGsWKRwlF6jqqgfj6FLCB1rO0mmk2Vf7et7NIUEIIRWsok79TElOiEU1jTlbTzTBqDegjMQOYcL9UxgZQXyvdtxtsuhnnabvOnPvd6pf3eO0o05LLW3NXG4msrKg3BQVEOwV_ABd_HnUQ
{
  "Email" : "testNonAdmin@example.com",
  "suspendUser" : false
}
###
