@CSIT_314_Group_HostAddress = http://localhost:5135

GET {{CSIT_314_Group_HostAddress}}/FRA/
Accept: application/json

###

POST {{CSIT_314_Group_HostAddress}}/CreateUserAccount
Content-Type: application/json
Accept: application/json
{
  "Name": "fAbiAn",
  "Email": "fabian@example.com",
  "PhoneNumber": "92342342",
  "Password": "MySecret123!",
  "Profile" : "admin"
}

###

POST {{CSIT_314_Group_HostAddress}}/Auth/Login
Content-Type : application/json
Accept: application/json
{
    "Email": "fabian@example.com",
     "Password": "MySecret123!"
}
###


GET {{CSIT_314_Group_HostAddress}}/ViewUserAccount
Content-Type : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6owGmMoe07pxhJxn1LL_a8W0RE2L7wIQ322NuAYFHK8EgJwZSRUsbN4vjVjehKBngXH2pMrgAcBBfOKmcfYCsGGBxjTsFP0mjXCG5sqzDDPEV6-fzEgN_pl-W9E8IAJiV3VJBSaPX54LejSVsY_nPsvokOYIuKT4fQNGPgHO4mPnIkFZwKEKMxlgdd8w5mmp_NLQ1nXb1CQK2oVrz-wQrb4mqICNtuIs49lJJicShbUtxQZcyQLNzM42F5cSFMjMB_20C6AlpXZ9-7trIknVUq0jt0_mNA8zRxD2XKHiZ3CNBQQrlV5WRFyeAhhhOg2rEoT_TFkssMcp9vkJ7FsHxt_9RbaZfcXzCVEPU2RaJPC4t1qivVb3_wvokx6Qvs2o3O6DjzFQMDlcRp2Yo_9XkEqym-I2GP8s5J88WPk0UAhLjLU0AftS1Zp0zm5b-YWdz9ZMmSd7faR-Vo2Jvd14QFsSEsqF9GLiT4rT4G0CNygvXczUVVssRfsqj5Ja7R3pq5snwObXtfOGmDrP-fNF5T9KQ5xqt-L5_Cv3-MPcJnMDB3e04EGCjsKAxIBEHqVUgOT_K0uTNw6fUJ7gNZHeJ5zW1fGPOsAHUfsyiacK7z4AA
###


GET {{CSIT_314_Group_HostAddress}}/SearchUserAccount?nameOrEmailOrPhone=fAbIan@eXAmple.cOm
Content-Type : application/json

###

GET {{CSIT_314_Group_HostAddress}}/Auth/Logout
Content-Type : application/json


###
GET {{CSIT_314_Group_HostAddress}}/CreateUserAccount/Ping
Accept: application/json

###