@CSIT_314_GROUP = http://localhost:5135

POST {{CSIT_314_GROUP}}/api/FavouriteFundraiser
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6oew_YugF30W4M4AUwgcHMD8Guxi2mVUYw93PVAwKGPlTFMz9IhhLyQVI4HsBS9PGlEj9eR7uDIc_jviECOpCQ6FeiyQGJXsVA1ios0YRSsUhLiW_r-dThQikdf2dgxq8qtl9EvdHHxyqlkeK29MVbjAY98MpHJCflz0YPgMZnJItvUv-8HbL6CcfcDN98u8TsWISFgV0MMuwSbyKiVa2AACsyW-41BGL530-uJSqG41YZJvilU8mIrS8KKeuW4Szb5Egj2Jl1AUXSyYIbg6RNRXN7LyZH7xY1KvP8-uUhh4tLT-54sanNeJwhJb4IF8YVwOaOdCl1909Q1mpfLHqJZnxoLyhKlx8TIbndBZVQ3SG9x69WlSp4jzCgIu8GYZI_91MTZWSTOhz_MnumqS0mJpc6rAM3jpPdGEHPVmfVUIv4AAgCOmEjj_Qak7WtUCskmJUYhtV-aX-BEgqWNz-rd4ao0dQvzEwjZexmht5K5Ti2n4fz49ZD7dTl6FAQHV6aXY9KTsoP6eduZxmWY1yKoOkYNaiYhgQjZcjm2j9LDhPXeZ6IK7NvCRZXnnPpGFtqesrtGlIgvR6bqme1eSwG3MJuCY85R74HCZDxAXE0X1204_uYDwQsg1Ie4jEvAGfQ
{
  "fraId" : 5
}
###

GET {{CSIT_314_GROUP}}/api/ViewFundraiserFavourites
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0giO9cegzo3yb9IieioSS-SIY4PkqBY6HVtOEMkmVK8Od7edk-S1A1ZHD-PcoVy4bc5yYvXKktMgfNcRCulkLgTftusBzb8myOQYRg4hWPSPepwp7OEK4x2n0RrJOHqLRwCEzjW8IDNEFdpmCtckOX0RPF8xK-E6vpUVzW3T5KX2eel217gs3WH8slsJEUPPW1CtIORoxi28ohGUvar4Ga_4YP-Q1twgrdGof-PlXt-vHg7IU5vwKpPu0WtTGOKRcFr2Q-W5GeqV12Rm1IgBUFkTL_i-_Wr2-Xt_IF-UgQHRFgeftDQiJ1wjdkwV4XmoL8EwY-wXBTUfzZTCoNVSRzngLjCDBgo8WCJQLi7qpA_xdo_rj-x3NcAQj2LLzeFhfJzd9VwklW8RADnPVbBo0LrxKDdyaJ_uwqOIRnEHsJT6tHSE7ZbHs_OzPuWoNt4UIhPyjr6yd945jaIQBOqccfPhAluL81hbRuSxeW6xB3TN12wxeVxnyYkwZvs6tgW0zLTkRZOPCyfsIebjPR1cJiF_3V46BD3uoAA-38GNyhT86iYdntzPREGPEs7XPE3QWOIKiHx76-m8Wl9wF8YxWFft-hBG-JhWye_cFUEzCTNGgJbsudAakeOtJd40DNjs
###

GET {{CSIT_314_GROUP}}/api/ViewAmtOfFavourites
Content-Type: application/json
Accept: application/json
{
  "fraId" : 3
}
###
GET {{CSIT_314_GROUP}}/api/SearchFavourite?fraName=test2
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6oew_YugF30W4M4AUwgcHMD8Guxi2mVUYw93PVAwKGPlTFMz9IhhLyQVI4HsBS9PGlEj9eR7uDIc_jviECOpCQ6FeiyQGJXsVA1ios0YRSsUhLiW_r-dThQikdf2dgxq8qtl9EvdHHxyqlkeK29MVbjAY98MpHJCflz0YPgMZnJItvUv-8HbL6CcfcDN98u8TsWISFgV0MMuwSbyKiVa2AACsyW-41BGL530-uJSqG41YZJvilU8mIrS8KKeuW4Szb5Egj2Jl1AUXSyYIbg6RNRXN7LyZH7xY1KvP8-uUhh4tLT-54sanNeJwhJb4IF8YVwOaOdCl1909Q1mpfLHqJZnxoLyhKlx8TIbndBZVQ3SG9x69WlSp4jzCgIu8GYZI_91MTZWSTOhz_MnumqS0mJpc6rAM3jpPdGEHPVmfVUIv4AAgCOmEjj_Qak7WtUCskmJUYhtV-aX-BEgqWNz-rd4ao0dQvzEwjZexmht5K5Ti2n4fz49ZD7dTl6FAQHV6aXY9KTsoP6eduZxmWY1yKoOkYNaiYhgQjZcjm2j9LDhPXeZ6IK7NvCRZXnnPpGFtqesrtGlIgvR6bqme1eSwG3MJuCY85R74HCZDxAXE0X1204_uYDwQsg1Ie4jEvAGfQ
