@CSIT_314_GROUP = http://localhost:5135

POST {{CSIT_314_GROUP}}/api/FavouriteFundraiser
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6p7T1X7HFdX8__51aAHgVdzFY2PuaoqRjUNntVG86dOXCzomrHkX_15ncc17z_d_VQ_ANYL8gmPwkdeP58a4njxqVyxVmwpai2ROueY-7Gk9lfUZWAf5Dmxay7qvRgqtvBrJFyeIQq3haQGWfECbt8xGUx0EHIwROABc17bCPEJ0G9bPSAgCwaKNIK94ezmCkeYSQ0h6relKSOgrHZUMhcM0CIJeNMlerYOGGzpPwWeIhs6clNWilpAWdAXjMKWD_TLwC31QOIP0F3T3Zl4tehvchFITeR_vof0gqwCFEfL6MfLboyldjgeP1JYLCxnW7mqp7LWydLLKnYJUvvNONOeELBzlUBGCjf4vQKlsjIc9w62mqP4utNPuW2pCesdG3OSMAlsV_6ddpG_5pGW-WD659P6BsD8xYBIGuVi7eFJLwj7FeclJih8SJIxMsO_AZsacGXpBywXNrAqlbVPy825BJcXo239V6XFVwGND7WTMxDOQWy8K8l2sz454__QdqI_aijLxMUAH_hfVsuWzJFjcRLniTWP7aQymPYcUo9UcQrczJofudspvuiJsFNVERgxFcEjIl9_3myn9zJtr8qs58sqnUCG7A_dO0ZWYMSHmw
{
  "fraId" : 3
}
###

GET {{CSIT_314_GROUP}}/api/ViewFundraiserFavourites
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6p7T1X7HFdX8__51aAHgVdzFY2PuaoqRjUNntVG86dOXCzomrHkX_15ncc17z_d_VQ_ANYL8gmPwkdeP58a4njxqVyxVmwpai2ROueY-7Gk9lfUZWAf5Dmxay7qvRgqtvBrJFyeIQq3haQGWfECbt8xGUx0EHIwROABc17bCPEJ0G9bPSAgCwaKNIK94ezmCkeYSQ0h6relKSOgrHZUMhcM0CIJeNMlerYOGGzpPwWeIhs6clNWilpAWdAXjMKWD_TLwC31QOIP0F3T3Zl4tehvchFITeR_vof0gqwCFEfL6MfLboyldjgeP1JYLCxnW7mqp7LWydLLKnYJUvvNONOeELBzlUBGCjf4vQKlsjIc9w62mqP4utNPuW2pCesdG3OSMAlsV_6ddpG_5pGW-WD659P6BsD8xYBIGuVi7eFJLwj7FeclJih8SJIxMsO_AZsacGXpBywXNrAqlbVPy825BJcXo239V6XFVwGND7WTMxDOQWy8K8l2sz454__QdqI_aijLxMUAH_hfVsuWzJFjcRLniTWP7aQymPYcUo9UcQrczJofudspvuiJsFNVERgxFcEjIl9_3myn9zJtr8qs58sqnUCG7A_dO0ZWYMSHmw
###

GET {{CSIT_314_GROUP}}/api/ViewAmtOfFavourites
Content-Type: application/json
Accept: application/json
{
  "fraId" : 3
}
###
GET {{CSIT_314_GROUP}}/api/SearchFavourite?fraName=med
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6p7T1X7HFdX8__51aAHgVdzFY2PuaoqRjUNntVG86dOXCzomrHkX_15ncc17z_d_VQ_ANYL8gmPwkdeP58a4njxqVyxVmwpai2ROueY-7Gk9lfUZWAf5Dmxay7qvRgqtvBrJFyeIQq3haQGWfECbt8xGUx0EHIwROABc17bCPEJ0G9bPSAgCwaKNIK94ezmCkeYSQ0h6relKSOgrHZUMhcM0CIJeNMlerYOGGzpPwWeIhs6clNWilpAWdAXjMKWD_TLwC31QOIP0F3T3Zl4tehvchFITeR_vof0gqwCFEfL6MfLboyldjgeP1JYLCxnW7mqp7LWydLLKnYJUvvNONOeELBzlUBGCjf4vQKlsjIc9w62mqP4utNPuW2pCesdG3OSMAlsV_6ddpG_5pGW-WD659P6BsD8xYBIGuVi7eFJLwj7FeclJih8SJIxMsO_AZsacGXpBywXNrAqlbVPy825BJcXo239V6XFVwGND7WTMxDOQWy8K8l2sz454__QdqI_aijLxMUAH_hfVsuWzJFjcRLniTWP7aQymPYcUo9UcQrczJofudspvuiJsFNVERgxFcEjIl9_3myn9zJtr8qs58sqnUCG7A_dO0ZWYMSHmw

###

POST {{CSIT_314_GROUP}}/api/UnfavouriteFundraiser
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6p7T1X7HFdX8__51aAHgVdzFY2PuaoqRjUNntVG86dOXCzomrHkX_15ncc17z_d_VQ_ANYL8gmPwkdeP58a4njxqVyxVmwpai2ROueY-7Gk9lfUZWAf5Dmxay7qvRgqtvBrJFyeIQq3haQGWfECbt8xGUx0EHIwROABc17bCPEJ0G9bPSAgCwaKNIK94ezmCkeYSQ0h6relKSOgrHZUMhcM0CIJeNMlerYOGGzpPwWeIhs6clNWilpAWdAXjMKWD_TLwC31QOIP0F3T3Zl4tehvchFITeR_vof0gqwCFEfL6MfLboyldjgeP1JYLCxnW7mqp7LWydLLKnYJUvvNONOeELBzlUBGCjf4vQKlsjIc9w62mqP4utNPuW2pCesdG3OSMAlsV_6ddpG_5pGW-WD659P6BsD8xYBIGuVi7eFJLwj7FeclJih8SJIxMsO_AZsacGXpBywXNrAqlbVPy825BJcXo239V6XFVwGND7WTMxDOQWy8K8l2sz454__QdqI_aijLxMUAH_hfVsuWzJFjcRLniTWP7aQymPYcUo9UcQrczJofudspvuiJsFNVERgxFcEjIl9_3myn9zJtr8qs58sqnUCG7A_dO0ZWYMSHmw
{
"fraId" : 3
}