@CSIT_314_GROUP = http://localhost:5135

POST {{CSIT_314_GROUP}}/api/AddDonation
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pKnveIbaNv5YqC5Mhfll_QDwjw_HzRMl4MNagPlUwgGZHM_gF1YUUwipL65lgqJjeD70Yu6t5e9AVQT8v8zWzaVejkDxkN35iYCwdCpJJ_WvvtXljSBpnF1cQa3arm3QKnVD1vvrxnv6EHWGmA6h9IgvS9NXAwj01GwN7LkNIJWMJ_ExwacpX8Ai6f5xKJEuUp4OQVlyNhtR8wfYAxBNTKKnpWci92-HJu-YPYDcZA_y_AHodrUK9iOoegTGb_IZIiwg-UUznwJw7amSmgZF_ft88CvgZcnGATphARGqUzJHYhnv2PesHi_DIlB3YPf39ghYEVl-1QsvvL0EvO9_rP9OMZ6j3irV3rlrANcnP8L87bv4ipNSLjHYjW3TKIxZJvGuY8trYSGTXLvtGdNpS2PJN-BoFoLin48yBKAbTyrmeOflCC9jiksKDoumiOz5bJF_280rnJ5VNP0t6qNc7a9vnnoO97um8gvESIz6p8f3DNVtP6WNJIPpK8T-IZb-Gn1OZcWs0Fe9UhSneisPj6tx78WsRuOcacLOgCVI2eaEkVhliRT37uXUd-qaTR10-8l6MwB28y1YnGpIa72DUjT3t0G36cFfbrqVvtAaichaGAANYx0Y5-OdgT_7BsNCQ

{
  "FraId": 3,
  "AmtDonatedByUser" : 74
}
###
GET {{CSIT_314_GROUP}}/api/ViewDonationHistory
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pKnveIbaNv5YqC5Mhfll_QDwjw_HzRMl4MNagPlUwgGZHM_gF1YUUwipL65lgqJjeD70Yu6t5e9AVQT8v8zWzaVejkDxkN35iYCwdCpJJ_WvvtXljSBpnF1cQa3arm3QKnVD1vvrxnv6EHWGmA6h9IgvS9NXAwj01GwN7LkNIJWMJ_ExwacpX8Ai6f5xKJEuUp4OQVlyNhtR8wfYAxBNTKKnpWci92-HJu-YPYDcZA_y_AHodrUK9iOoegTGb_IZIiwg-UUznwJw7amSmgZF_ft88CvgZcnGATphARGqUzJHYhnv2PesHi_DIlB3YPf39ghYEVl-1QsvvL0EvO9_rP9OMZ6j3irV3rlrANcnP8L87bv4ipNSLjHYjW3TKIxZJvGuY8trYSGTXLvtGdNpS2PJN-BoFoLin48yBKAbTyrmeOflCC9jiksKDoumiOz5bJF_280rnJ5VNP0t6qNc7a9vnnoO97um8gvESIz6p8f3DNVtP6WNJIPpK8T-IZb-Gn1OZcWs0Fe9UhSneisPj6tx78WsRuOcacLOgCVI2eaEkVhliRT37uXUd-qaTR10-8l6MwB28y1YnGpIa72DUjT3t0G36cFfbrqVvtAaichaGAANYx0Y5-OdgT_7BsNCQ

###

GET {{CSIT_314_GROUP}}/api/SearchDonationHistory?fraName=med
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pKnveIbaNv5YqC5Mhfll_QDwjw_HzRMl4MNagPlUwgGZHM_gF1YUUwipL65lgqJjeD70Yu6t5e9AVQT8v8zWzaVejkDxkN35iYCwdCpJJ_WvvtXljSBpnF1cQa3arm3QKnVD1vvrxnv6EHWGmA6h9IgvS9NXAwj01GwN7LkNIJWMJ_ExwacpX8Ai6f5xKJEuUp4OQVlyNhtR8wfYAxBNTKKnpWci92-HJu-YPYDcZA_y_AHodrUK9iOoegTGb_IZIiwg-UUznwJw7amSmgZF_ft88CvgZcnGATphARGqUzJHYhnv2PesHi_DIlB3YPf39ghYEVl-1QsvvL0EvO9_rP9OMZ6j3irV3rlrANcnP8L87bv4ipNSLjHYjW3TKIxZJvGuY8trYSGTXLvtGdNpS2PJN-BoFoLin48yBKAbTyrmeOflCC9jiksKDoumiOz5bJF_280rnJ5VNP0t6qNc7a9vnnoO97um8gvESIz6p8f3DNVtP6WNJIPpK8T-IZb-Gn1OZcWs0Fe9UhSneisPj6tx78WsRuOcacLOgCVI2eaEkVhliRT37uXUd-qaTR10-8l6MwB28y1YnGpIa72DUjT3t0G36cFfbrqVvtAaichaGAANYx0Y5-OdgT_7BsNCQ
