@CSIT_314_Group_HostAddress = http://localhost:5135

###
POST {{CSIT_314_Group_HostAddress}}/api/CreateFundraiser
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pFzsJf5IyX4D_2p9nIVVbiSwIPJqrvMq5bzIF7lnF1_Co4c2ZjteAUqSsjT7twB9VlDcaVE7ph_ezJHY_p4HUjwbG9yldhtcVeMFq9RNoBhZ1Z7-klagSmCceknas-1jHhJEHMJrNb5jUDfb8Ey1Pb7HPqfVNoS5lODhmNHKgMlAlx-u_ZW3KlJyv1dTGYxbomsxoe9YWZ-gHA07QuRiBBGDPWySoRBbf_Mlt8Rnuu9apCfMdsDvHTfd37EabQfCneRBCuEXROlwYS2XTuN9sbrU8A9vqVBENYiFetY85Wtn7D0NFRcndD_BACKRxP4V1DlWCs--jV2f9QOi1u2pJ7tfwyZiZgodnAjHdJi-_TFWcuUgG8y0FPKUpY---jJoo78zolhnGwGcnzwrAzfZA2UOhJV4xI5wOKe1ovDoSakkjT-U4RkfV8ecCBYgb2hUpyWzEqP2k09kaNLafI_U8Sit7IX6MdMsUfPsg0_Ha7jWxUfLVANnVoCWsu9Ff7lANCumxt1gPmFQm1XDMTE57WpaNLK0bKjuvHV3SAzzNHuFTqvEq_XqCJ047Imekoqm-ugnT2yYAcqPhpaY0feAe-gOq6UXRPsJODQmdJ0paPs2ymEq3WA-MKokk9C1-nYgI
{
  "Name" : "test5",
  "Description" : "ThisIsATestFraDesc5",
  "deadline": "10-01-2015",
  "amtRequested" : "12121",
  "fraCategoryId" : 2
}
###

GET {{CSIT_314_Group_HostAddress}}/api/ViewAllFundraiser
Content-Type: application/json
Accept: application/json
###
GET {{CSIT_314_Group_HostAddress}}/api/ViewMyFundraisers
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6o86JVl71Qj-gcPUQpGbHUyJ_Pbc3wiIsOE11f6JcfnUSGW-289E108L4LALrvC6zXO-Zo7FTStdbEnC1d9x9NcWl1SNV3ofaslIdI4nYSRRZZLPDg8Y4cn5NNFEMA5m-VxcBkjhhWL78_egIG-VgJj9zEAf5ZiaTdftodd84ddXt9ezAsZvWlU6UYRbrgVl2HAGSGTGOTF8KXcvHBj4U0pawm-ZoCjjuAeN18ojrl9LCx76CmF3JCyyFON8AxVN1awd0vScyz9YsGG_0K-R0MdyfWlfRFNPsvM3xUPwQ8O0FuPq1hhv7r0Mc7gukOEMZQm6Ue37OjZ9T_3ga7ZCRNlIWGrKF_00PrNLba2o3-iNo79Fhxfi2LOMAQFM1eGu3Hv_unsc2VQ68GbN2Sxa3ZkGRT_UYvhRst9K_dUvAfD95ZhtHtAUVyomJU5sxDoU2sSZ7zVVkdTeqg9vqSmFpMgGPJb1ORsDGu305Yi6lNzFzhVS0XlZSlf0VbvNbG0toDEXOyVGFoPpmitRzz7ic1kgl7tuV5njDfzyMGfMTPMRP8IMSrZHOtrh9CuCgV4M7z_MRmG9nlVwQ8eoxl4pbVJyay9DtryZTyR5drZOrApspiFc21CdqGpr7JvcjfRTHA
###

PUT {{CSIT_314_Group_HostAddress}}/api/UpdateFundraiser
Content-Type : application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6o86JVl71Qj-gcPUQpGbHUyJ_Pbc3wiIsOE11f6JcfnUSGW-289E108L4LALrvC6zXO-Zo7FTStdbEnC1d9x9NcWl1SNV3ofaslIdI4nYSRRZZLPDg8Y4cn5NNFEMA5m-VxcBkjhhWL78_egIG-VgJj9zEAf5ZiaTdftodd84ddXt9ezAsZvWlU6UYRbrgVl2HAGSGTGOTF8KXcvHBj4U0pawm-ZoCjjuAeN18ojrl9LCx76CmF3JCyyFON8AxVN1awd0vScyz9YsGG_0K-R0MdyfWlfRFNPsvM3xUPwQ8O0FuPq1hhv7r0Mc7gukOEMZQm6Ue37OjZ9T_3ga7ZCRNlIWGrKF_00PrNLba2o3-iNo79Fhxfi2LOMAQFM1eGu3Hv_unsc2VQ68GbN2Sxa3ZkGRT_UYvhRst9K_dUvAfD95ZhtHtAUVyomJU5sxDoU2sSZ7zVVkdTeqg9vqSmFpMgGPJb1ORsDGu305Yi6lNzFzhVS0XlZSlf0VbvNbG0toDEXOyVGFoPpmitRzz7ic1kgl7tuV5njDfzyMGfMTPMRP8IMSrZHOtrh9CuCgV4M7z_MRmG9nlVwQ8eoxl4pbVJyay9DtryZTyR5drZOrApspiFc21CdqGpr7JvcjfRTHA
{
  "fraId" : 2,
  "fraCategoryId": 5
}
###

DELETE {{CSIT_314_Group_HostAddress}}/api/DeleteFundraiser?fundraiserId=5
Content-Type : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pFzsJf5IyX4D_2p9nIVVbiSwIPJqrvMq5bzIF7lnF1_Co4c2ZjteAUqSsjT7twB9VlDcaVE7ph_ezJHY_p4HUjwbG9yldhtcVeMFq9RNoBhZ1Z7-klagSmCceknas-1jHhJEHMJrNb5jUDfb8Ey1Pb7HPqfVNoS5lODhmNHKgMlAlx-u_ZW3KlJyv1dTGYxbomsxoe9YWZ-gHA07QuRiBBGDPWySoRBbf_Mlt8Rnuu9apCfMdsDvHTfd37EabQfCneRBCuEXROlwYS2XTuN9sbrU8A9vqVBENYiFetY85Wtn7D0NFRcndD_BACKRxP4V1DlWCs--jV2f9QOi1u2pJ7tfwyZiZgodnAjHdJi-_TFWcuUgG8y0FPKUpY---jJoo78zolhnGwGcnzwrAzfZA2UOhJV4xI5wOKe1ovDoSakkjT-U4RkfV8ecCBYgb2hUpyWzEqP2k09kaNLafI_U8Sit7IX6MdMsUfPsg0_Ha7jWxUfLVANnVoCWsu9Ff7lANCumxt1gPmFQm1XDMTE57WpaNLK0bKjuvHV3SAzzNHuFTqvEq_XqCJ047Imekoqm-ugnT2yYAcqPhpaY0feAe-gOq6UXRPsJODQmdJ0paPs2ymEq3WA-MKokk9C1-nYgI

###

GET {{CSIT_314_Group_HostAddress}}/api/SearchFundraiser?name=test
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6oQjeNUh5PNnRl85b-_3223ojQRhZhDk533tdarqcgStv5KIAs19_hlsVB6jTgOfzAjj_Xi4__PLdmoW0fI5DcFwB0aa9B85jZyjRtBZAIwSLUKZVbJ9LWdVmDN4iu61iLza2H-_a5xKIVRUoS-T_eQkBO1JwO3cy1Hi-n3IQTvEVcwFFPNFS_lK-BGJxP4aOHmX1NY0Ld1QW316_Wnxru5Zm5uGQGLbTecfI2DTe5eHiYvvbA1oDf9TKElqC_3C7UHbcFMhbyPpNiPa1rauVRwyF7UGAaxxI3UAfgudkfl6O_J3i2CUnK6KUME16-GOEgDmcrXtBpZZ7HZDVXJDjNT6aTPmkErWnM6oCTxo4AbZSQiuJro2OD3_6tSFZDUtdg0qwqeEalhxNyh5gihb0J-cwzkPA0OQtXXTDCbSn9m7UTeI9As7SlNXOHv3M04ICNnAYNlxBJY8RkQVrhbLenrXq0X5sW3XyqegLqaXxhCYsOycJNDDMcLDZ9g0SfilLGlV7Q9lW2J9hkoucdUPB9x6uZHUAuaCuzs3KAX7LFDCoWCB7B9x79lRhjYU5ncG-0DttQgTRJ3bEmsB8-9-UP37Py_rHnFv2nE2oMGtO2Upxv777Ip5OA8w09yPnDRLg4

###

GET {{CSIT_314_Group_HostAddress}}/api/ViewOneFundraiser?fraId=5
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6oQjeNUh5PNnRl85b-_3223ojQRhZhDk533tdarqcgStv5KIAs19_hlsVB6jTgOfzAjj_Xi4__PLdmoW0fI5DcFwB0aa9B85jZyjRtBZAIwSLUKZVbJ9LWdVmDN4iu61iLza2H-_a5xKIVRUoS-T_eQkBO1JwO3cy1Hi-n3IQTvEVcwFFPNFS_lK-BGJxP4aOHmX1NY0Ld1QW316_Wnxru5Zm5uGQGLbTecfI2DTe5eHiYvvbA1oDf9TKElqC_3C7UHbcFMhbyPpNiPa1rauVRwyF7UGAaxxI3UAfgudkfl6O_J3i2CUnK6KUME16-GOEgDmcrXtBpZZ7HZDVXJDjNT6aTPmkErWnM6oCTxo4AbZSQiuJro2OD3_6tSFZDUtdg0qwqeEalhxNyh5gihb0J-cwzkPA0OQtXXTDCbSn9m7UTeI9As7SlNXOHv3M04ICNnAYNlxBJY8RkQVrhbLenrXq0X5sW3XyqegLqaXxhCYsOycJNDDMcLDZ9g0SfilLGlV7Q9lW2J9hkoucdUPB9x6uZHUAuaCuzs3KAX7LFDCoWCB7B9x79lRhjYU5ncG-0DttQgTRJ3bEmsB8-9-UP37Py_rHnFv2nE2oMGtO2Upxv777Ip5OA8w09yPnDRLg4
###