@CSIT_314_GROUP = http://localhost:5135

POST {{CSIT_314_GROUP}}/api/AddDonation?
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6r4LkuYn00OT-WoMGWUEONpf9FIIrqP0_AM38ThmUqQL2bNglWvE7XTCsTEpUGgRieeZNJAQ2n4b3UyT7vCMh5zu-Wtep4OySIHxAW_BabyoroEHkQE5q9i1s4_rFnW9tkB2qIoiGsjRu2Zjszo8hOJUxZhZR6L-iAea_BH-IcduknGoaECT-W2eR5b1Q9eZVPC8DgOWs9TRvvRw6IssUpN0_i9736IdXQj6piTzfOhGj6KCz6ykx9V33jKCff9kl8cNjOdPK4N-2fEIoBrIzDxr1ldc6DYb1BVJ_3_4OoCutUJYxgg7gO29Br-f1bgRK3WNLncxsZtUfpjCsAyi1YseVE6eJT8oJQm4aA4-r4kI1wAgA62Gyae_8KB-TTzlv1G9EbF1d9W-vTesQTJTkJmRI3sdgM8MVUi1dee-PxZtp2QDffAMUiHuyRibGtQb6E8f2u7PbEh9NBINpecDusGx01BQ3yynV0rs6DZ3JZMZ5bflBabGsesx8JuF4dPz-pu2vMGzYuvUyQnp5aZuv-sSVCzJySTwx-SbxyT1pFs8FZI5Ddagq7S0u3UtlYCqDZAjif82fA9CMXZ6wn4i0rbpXbsyBJ_GrA3QNYK3UJeEw
 {
   "id": 12,
   "AmtDonated" : 128
 }
###
GET {{CSIT_314_GROUP}}/api/ViewDonationHistory
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6r4LkuYn00OT-WoMGWUEONpf9FIIrqP0_AM38ThmUqQL2bNglWvE7XTCsTEpUGgRieeZNJAQ2n4b3UyT7vCMh5zu-Wtep4OySIHxAW_BabyoroEHkQE5q9i1s4_rFnW9tkB2qIoiGsjRu2Zjszo8hOJUxZhZR6L-iAea_BH-IcduknGoaECT-W2eR5b1Q9eZVPC8DgOWs9TRvvRw6IssUpN0_i9736IdXQj6piTzfOhGj6KCz6ykx9V33jKCff9kl8cNjOdPK4N-2fEIoBrIzDxr1ldc6DYb1BVJ_3_4OoCutUJYxgg7gO29Br-f1bgRK3WNLncxsZtUfpjCsAyi1YseVE6eJT8oJQm4aA4-r4kI1wAgA62Gyae_8KB-TTzlv1G9EbF1d9W-vTesQTJTkJmRI3sdgM8MVUi1dee-PxZtp2QDffAMUiHuyRibGtQb6E8f2u7PbEh9NBINpecDusGx01BQ3yynV0rs6DZ3JZMZ5bflBabGsesx8JuF4dPz-pu2vMGzYuvUyQnp5aZuv-sSVCzJySTwx-SbxyT1pFs8FZI5Ddagq7S0u3UtlYCqDZAjif82fA9CMXZ6wn4i0rbpXbsyBJ_GrA3QNYK3UJeEw

###

GET {{CSIT_314_GROUP}}/api/SearchDonationHistory?fraName=test
Content-Type: application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6r4LkuYn00OT-WoMGWUEONpf9FIIrqP0_AM38ThmUqQL2bNglWvE7XTCsTEpUGgRieeZNJAQ2n4b3UyT7vCMh5zu-Wtep4OySIHxAW_BabyoroEHkQE5q9i1s4_rFnW9tkB2qIoiGsjRu2Zjszo8hOJUxZhZR6L-iAea_BH-IcduknGoaECT-W2eR5b1Q9eZVPC8DgOWs9TRvvRw6IssUpN0_i9736IdXQj6piTzfOhGj6KCz6ykx9V33jKCff9kl8cNjOdPK4N-2fEIoBrIzDxr1ldc6DYb1BVJ_3_4OoCutUJYxgg7gO29Br-f1bgRK3WNLncxsZtUfpjCsAyi1YseVE6eJT8oJQm4aA4-r4kI1wAgA62Gyae_8KB-TTzlv1G9EbF1d9W-vTesQTJTkJmRI3sdgM8MVUi1dee-PxZtp2QDffAMUiHuyRibGtQb6E8f2u7PbEh9NBINpecDusGx01BQ3yynV0rs6DZ3JZMZ5bflBabGsesx8JuF4dPz-pu2vMGzYuvUyQnp5aZuv-sSVCzJySTwx-SbxyT1pFs8FZI5Ddagq7S0u3UtlYCqDZAjif82fA9CMXZ6wn4i0rbpXbsyBJ_GrA3QNYK3UJeEw
