@CSIT_314_Group_HostAddress = http://localhost:5135


POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ
{
  "name":"abcde",
  "email": "abcde@example.com",
  "phoneNumber": "12354125",
  "hashedPassword": "password123!",
  "profileId" : 2,
  "isSuspended" : false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/Auth/Login?email=admin01@example.com
Content-Type: application/json
Accept: application/json
"password123!"
###

GET {{CSIT_314_Group_HostAddress}}/api/ViewAllUserAccount
Accept : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ

###

GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount?userId=2
Content-Type : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ


###

POST {{CSIT_314_Group_HostAddress}}/api/SearchUserAccount?query=plat
Content-Type : application/json
Accept : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ


###

GET {{CSIT_314_Group_HostAddress}}/api/Auth/Logout
Content-Type : application/json

###

GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount?userId=2
Content-Type: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ

###
PUT {{CSIT_314_Group_HostAddress}}/api/SuspendUserAccount?userId=7&suspendUser=true
Content-Type : application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ

###

POST {{CSIT_314_Group_HostAddress}}/api/UpdateUserAccount
Content-Type : application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6q0yUzo-1m_bfuKQh7Li1mF1iUOWMLfRO9MeiBz8GOwfMHkxkNHwCQoM9nwoYEuY7uSqJVwPJO5zPxwg6PHJlHLK0vdKlu7a6ee48u_lMN9AW94Fce43LWjPRCe294iDX4Ctfukx5dnZQgfTf-eZgKfhNIZ7CweZCBQqz4sLrfPkc6N6iIvbqfybC3TnI7N9WJQMLkh74voR3UFp03-yEdWX6dNPTxOgLC4W0Rx3JQXMYdLnYrsTZ1DEwyuML3rCnau78a9BA2AHuYFwiE7mIKwPIJrZYKXvHdIkxuADiBXft4wHK38F4FUnOYz97dosXnIzaZFFANZWV_SQuB-7kWJIvW-D2G2DflPphl4v__u8hh76TyEdWHuvrTVMLJ8Te0T7vyPwj3-fICW0MKkQfYDum9v61pt3k5bDZi63SvSOK3dBlzyTeTk2zc1kg4_bCsv1Tn-TZYv4oSo5vNbvN3ynLYbfElWkW0G97GCIZj1-CEYii0LtmePPOmSUKquU42HyBkugZ7GXym-3foARPCK9VpENIJun9Pk5StDLGd2yPo8_b-7xeOFj_pnkMZdcDxwOKwfThTVDfLc87eACxPAaZNglv8XvavIjcfobZOypQ
{
  "Id" : 2,
  "Name": "edwin",
  "profileName" : "donee"
}
###


GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount?userId=4
Content-Type : application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pPowVubAT5Coaq-BfEjV_LYWKNQts3Z1MVv-QHkg2Ck45ZuJN1xnK7sg3hm_wDBaG2X-cXxYMNQzoC-gHdHTXwZ84GwQi32QWF_w3E_epMfFMvvrmtGTyGgZiOu0_DYUUzpuavtHE5bqqgnwSckYlWcoF35NBsxhqLmfiI7AA_TcptZOHMbK29JxTDb4uwu8nsYs4tTqyLqz4VyzCteA4ChvlYUxa5KySZCg3T60ChyM54GSrnJSpgG1WPUiOtDsjDj4gHAOxQN-Nr6Ip0RBjLrqoo2CA28qSudcCG_tbOSrDHvcvvcA1cH9AYP4Mod9UbSvAMqOgLSKJqy7S8TP0h7vhAOKvCBNvcKq2Kw-X3998v9o6ak7vk1eDYR3gJ92R4WmpGaCiDWjeJzs6pEDITPFeIgRX_dbO4sSa-n-IslnbNK8d5juzgl7JJx7GbwhZLCL-g5NlwXAciYjRAtiO7NhxWSyAYmJ2AAgvvLh4fLO8Np6Q8z_FXxdRfwcDZXmzYjKPwG9JIfuMTdeTEvpoMyyVtD2ipcoaf-P385ghGnufPJHev4tPHTV66rT0fG_IerNdytih6o-Qr2Fh3da9_ewXJYa1mkrEut3E9R77SsQ

###
POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json
{
  "Name": "admin01",
  "Email": "admin01@example.com",
  "PhoneNumber": "81111111",
  "Password": "password123!",
  "ProfileName": "admin",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "platformmanager01",
  "Email": "platformmanager01@example.com",
  "PhoneNumber": "82222222",
  "Password": "password123!",
  "ProfileName": "platform manager",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "donee01",
  "Email": "donee01@example.com",
  "PhoneNumber": "83333333",
  "Password": "password123!",
  "ProfileName": "donee",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "fundraisermanager01",
  "Email": "fundraisermanager01@example.com",
  "PhoneNumber": "84444444",
  "Password": "password123!",
  "ProfileName": "fundraiser manager",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "donee02",
  "Email": "donee02@example.com",
  "PhoneNumber": "85555555",
  "Password": "password123!",
  "ProfileName": "donee",
  "IsSuspended": false
}