@CSIT_314_Group_HostAddress = http://localhost:5135


POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6psGJ74GNlHmSJQEcRR8XPf0sVtcyldyKSL8s41fcO8RpM4ih-wfgJiCed2JnytgrngQE94Ha4YW3FWxU11v9H9cBwPn4zkT9MnD1CLA-ZxG1Wyx_EqEQiSRNvpCL7bpVIAu4IVOm6ZSoeisuBGdvqeLtYd3EInf6_PTrXSbftOQYNPKOZwXP0gBsB1IX_tss4KtuFFPdw2LBi-1WfnB7swh28RDigzbo5gEE64jFVJUDtXuYkrQ4jXRXn6hGbOWtOJUKLkIkydUsQagbHvfUPfZrEUNZ3BZymgy3tWRuzFcuuhbFtYsv8IXd5LNPeAh2HBTU4XtkyIKDtu9I-CKvFo7Ywwu-MYMB1nIVUXQwzdG5MVZuDnLsHhOa_rAw2Bc2_7x_cYvtdn8fXwE7xgYwFG24zHGYz6R3e3LfZzJxpCjXvWiv0Sk5WwVVQEsIC8QC27Zp1ZAL8kZr9FIZ_Ds_PMDIqVgVUY-RkrqEgMBpl9cHnWTLytTFb47wR4Msy-UEJLsjxSd7nO3bXl7UX2Uwfz-5ccjot7RNEKwlx1Q8KkXOoD-OR1b8tBn_vEdOsxqFPfcffHHQsJ0zkhG-vCw-fd5G3b1Xss7eQqeCBpQVa8kw

{
  "Name": "bce123",
  "Email": "bce123@example.com",
  "PhoneNumber": "23432534",
  "Password": "password123!",
  "ProfileName" : "FUNDRAISER manager",
  "IsSuspended" : false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/Auth/Login
Content-Type: application/json
Accept: application/json

{
    "Email": "donee01@example.com",
     "Password": "password123!"
}
###

GET {{CSIT_314_Group_HostAddress}}/api/ViewAllUserAccount
Accept : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6psGJ74GNlHmSJQEcRR8XPf0sVtcyldyKSL8s41fcO8RpM4ih-wfgJiCed2JnytgrngQE94Ha4YW3FWxU11v9H9cBwPn4zkT9MnD1CLA-ZxG1Wyx_EqEQiSRNvpCL7bpVIAu4IVOm6ZSoeisuBGdvqeLtYd3EInf6_PTrXSbftOQYNPKOZwXP0gBsB1IX_tss4KtuFFPdw2LBi-1WfnB7swh28RDigzbo5gEE64jFVJUDtXuYkrQ4jXRXn6hGbOWtOJUKLkIkydUsQagbHvfUPfZrEUNZ3BZymgy3tWRuzFcuuhbFtYsv8IXd5LNPeAh2HBTU4XtkyIKDtu9I-CKvFo7Ywwu-MYMB1nIVUXQwzdG5MVZuDnLsHhOa_rAw2Bc2_7x_cYvtdn8fXwE7xgYwFG24zHGYz6R3e3LfZzJxpCjXvWiv0Sk5WwVVQEsIC8QC27Zp1ZAL8kZr9FIZ_Ds_PMDIqVgVUY-RkrqEgMBpl9cHnWTLytTFb47wR4Msy-UEJLsjxSd7nO3bXl7UX2Uwfz-5ccjot7RNEKwlx1Q8KkXOoD-OR1b8tBn_vEdOsxqFPfcffHHQsJ0zkhG-vCw-fd5G3b1Xss7eQqeCBpQVa8kw

###

GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount
Content-Type : application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6oQjeNUh5PNnRl85b-_3223ojQRhZhDk533tdarqcgStv5KIAs19_hlsVB6jTgOfzAjj_Xi4__PLdmoW0fI5DcFwB0aa9B85jZyjRtBZAIwSLUKZVbJ9LWdVmDN4iu61iLza2H-_a5xKIVRUoS-T_eQkBO1JwO3cy1Hi-n3IQTvEVcwFFPNFS_lK-BGJxP4aOHmX1NY0Ld1QW316_Wnxru5Zm5uGQGLbTecfI2DTe5eHiYvvbA1oDf9TKElqC_3C7UHbcFMhbyPpNiPa1rauVRwyF7UGAaxxI3UAfgudkfl6O_J3i2CUnK6KUME16-GOEgDmcrXtBpZZ7HZDVXJDjNT6aTPmkErWnM6oCTxo4AbZSQiuJro2OD3_6tSFZDUtdg0qwqeEalhxNyh5gihb0J-cwzkPA0OQtXXTDCbSn9m7UTeI9As7SlNXOHv3M04ICNnAYNlxBJY8RkQVrhbLenrXq0X5sW3XyqegLqaXxhCYsOycJNDDMcLDZ9g0SfilLGlV7Q9lW2J9hkoucdUPB9x6uZHUAuaCuzs3KAX7LFDCoWCB7B9x79lRhjYU5ncG-0DttQgTRJ3bEmsB8-9-UP37Py_rHnFv2nE2oMGtO2Upxv777Ip5OA8w09yPnDRLg4
###
GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount
Content-Type : application/json


###

POST {{CSIT_314_Group_HostAddress}}/api/SearchUserAccount?query=donee
Content-Type : application/json
Accept : application/json


###

GET {{CSIT_314_Group_HostAddress}}/api/Auth/Logout
Content-Type : application/json

###

GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount
Content-Type: application/json
Cookie: .AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6qkiFCACxh8unpqeo_XXE6eN-xtp98ZMgtoYf7N8nKn5bS9LnrLPz71gaeYjtXnTMNSCua2HqsOivv4WpmEUSppq2jGje7JTkwOo_nCjz77l2RW4kRYiu1h36rI0Gwj0zbMrRgLaOHZvjLXhuH5JUjMNjsNG_Hw-e9SxccTaeQkHTy5vh_1yNqtyRdwc2yGClIEyzwS_2N8HUiAagB6dz62rk9RseSLKyQqew-RFVJ84a02npXTmcVJUhLzP3EgkxhxpEytYhj9FTpkRyrOpVz1-7HOOV1cR6I4g2x4UqgQJIyJVrcMq_Wtip8pj0d2kPoQR-_4GGQzvkYpw89nhIaeTXwxUqtWQFV2CCZ9t6Gx3lV3gM84Eyo1J5vhnYcbxHIlTdWUlrDJ1X0Aoafle1eRDzrenvYHUWc-79b-S04c7ZMrUfm4NjEOx9JxH8ok8h2IyXOCRXWutLHLYAPLbluV1qyPa7UMvkBRl_fIIzggkHAkdbrpvzL6nOxeLIfcXJ5J6hcmAlPjuguD3ZuwG8Il2RGviVNKClgZyVzqxcx1e8sspc4UCJu5YTxgDBsw7d-H9ZiwokZAaIYRDOzcFHROCBoDye9Q4CSatl1zaJyO_g

###
PUT {{CSIT_314_Group_HostAddress}}/api/SuspendUserAccount
Content-Type : application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pPowVubAT5Coaq-BfEjV_LYWKNQts3Z1MVv-QHkg2Ck45ZuJN1xnK7sg3hm_wDBaG2X-cXxYMNQzoC-gHdHTXwZ84GwQi32QWF_w3E_epMfFMvvrmtGTyGgZiOu0_DYUUzpuavtHE5bqqgnwSckYlWcoF35NBsxhqLmfiI7AA_TcptZOHMbK29JxTDb4uwu8nsYs4tTqyLqz4VyzCteA4ChvlYUxa5KySZCg3T60ChyM54GSrnJSpgG1WPUiOtDsjDj4gHAOxQN-Nr6Ip0RBjLrqoo2CA28qSudcCG_tbOSrDHvcvvcA1cH9AYP4Mod9UbSvAMqOgLSKJqy7S8TP0h7vhAOKvCBNvcKq2Kw-X3998v9o6ak7vk1eDYR3gJ92R4WmpGaCiDWjeJzs6pEDITPFeIgRX_dbO4sSa-n-IslnbNK8d5juzgl7JJx7GbwhZLCL-g5NlwXAciYjRAtiO7NhxWSyAYmJ2AAgvvLh4fLO8Np6Q8z_FXxdRfwcDZXmzYjKPwG9JIfuMTdeTEvpoMyyVtD2ipcoaf-P385ghGnufPJHev4tPHTV66rT0fG_IerNdytih6o-Qr2Fh3da9_ewXJYa1mkrEut3E9R77SsQ
{
  "userId": 7,
  "suspendUser" : false
}
###

POST {{CSIT_314_Group_HostAddress}}/api/UpdateUserAccount
Content-Type : application/json
Accept: application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6psGJ74GNlHmSJQEcRR8XPf0sVtcyldyKSL8s41fcO8RpM4ih-wfgJiCed2JnytgrngQE94Ha4YW3FWxU11v9H9cBwPn4zkT9MnD1CLA-ZxG1Wyx_EqEQiSRNvpCL7bpVIAu4IVOm6ZSoeisuBGdvqeLtYd3EInf6_PTrXSbftOQYNPKOZwXP0gBsB1IX_tss4KtuFFPdw2LBi-1WfnB7swh28RDigzbo5gEE64jFVJUDtXuYkrQ4jXRXn6hGbOWtOJUKLkIkydUsQagbHvfUPfZrEUNZ3BZymgy3tWRuzFcuuhbFtYsv8IXd5LNPeAh2HBTU4XtkyIKDtu9I-CKvFo7Ywwu-MYMB1nIVUXQwzdG5MVZuDnLsHhOa_rAw2Bc2_7x_cYvtdn8fXwE7xgYwFG24zHGYz6R3e3LfZzJxpCjXvWiv0Sk5WwVVQEsIC8QC27Zp1ZAL8kZr9FIZ_Ds_PMDIqVgVUY-RkrqEgMBpl9cHnWTLytTFb47wR4Msy-UEJLsjxSd7nO3bXl7UX2Uwfz-5ccjot7RNEKwlx1Q8KkXOoD-OR1b8tBn_vEdOsxqFPfcffHHQsJ0zkhG-vCw-fd5G3b1Xss7eQqeCBpQVa8kw
{
  "Id" : 2,
  "Name": "edwin",
  "Email": "",
  "PhoneNumber":"" ,
  "profileName" : "fundraiser MANAGER"
}
###


GET {{CSIT_314_Group_HostAddress}}/api/ViewUserAccount?userId=4
Content-Type : application/json
Cookie:.AspNetCore.Cookies=CfDJ8IKqO1yy17JCoelXFs6HW6pPowVubAT5Coaq-BfEjV_LYWKNQts3Z1MVv-QHkg2Ck45ZuJN1xnK7sg3hm_wDBaG2X-cXxYMNQzoC-gHdHTXwZ84GwQi32QWF_w3E_epMfFMvvrmtGTyGgZiOu0_DYUUzpuavtHE5bqqgnwSckYlWcoF35NBsxhqLmfiI7AA_TcptZOHMbK29JxTDb4uwu8nsYs4tTqyLqz4VyzCteA4ChvlYUxa5KySZCg3T60ChyM54GSrnJSpgG1WPUiOtDsjDj4gHAOxQN-Nr6Ip0RBjLrqoo2CA28qSudcCG_tbOSrDHvcvvcA1cH9AYP4Mod9UbSvAMqOgLSKJqy7S8TP0h7vhAOKvCBNvcKq2Kw-X3998v9o6ak7vk1eDYR3gJ92R4WmpGaCiDWjeJzs6pEDITPFeIgRX_dbO4sSa-n-IslnbNK8d5juzgl7JJx7GbwhZLCL-g5NlwXAciYjRAtiO7NhxWSyAYmJ2AAgvvLh4fLO8Np6Q8z_FXxdRfwcDZXmzYjKPwG9JIfuMTdeTEvpoMyyVtD2ipcoaf-P385ghGnufPJHev4tPHTV66rT0fG_IerNdytih6o-Qr2Fh3da9_ewXJYa1mkrEut3E9R77SsQ

###
POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json
{
  "Name": "admin01",
  "Email": "admin01@example.com",
  "PhoneNumber": "81111111",
  "Password": "password123!",
  "ProfileName": "admin",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "platformmanager01",
  "Email": "platformmanager01@example.com",
  "PhoneNumber": "82222222",
  "Password": "password123!",
  "ProfileName": "platform manager",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "donee01",
  "Email": "donee01@example.com",
  "PhoneNumber": "83333333",
  "Password": "password123!",
  "ProfileName": "donee",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "fundraisermanager01",
  "Email": "fundraisermanager01@example.com",
  "PhoneNumber": "84444444",
  "Password": "password123!",
  "ProfileName": "fundraiser manager",
  "IsSuspended": false
}

###

POST {{CSIT_314_Group_HostAddress}}/api/CreateUserAccount
Content-Type: application/json
Accept: application/json

{
  "Name": "donee02",
  "Email": "donee02@example.com",
  "PhoneNumber": "85555555",
  "Password": "password123!",
  "ProfileName": "donee",
  "IsSuspended": false
}